from abc import abstractmethod
from typing import Protocol

from src.core.types import CellData, GameResult, GameState, Move


class EngineMinimax(Protocol):
    def get_legal_moves(self, player: int) -> list[Move]: ...
    def apply_move(self, index: int) -> None: ...
    def undo_last_move(self) -> None: ...
    def get_board(self) -> list[CellData]: ...

    @property
    def current_player_id(self) -> int: ...
    @property
    @abstractmethod
    def game_result(self) -> GameResult: ...
    def set_state(self, state: GameState) -> None: ...

    def evaluate_position(self, player_id: int) -> float: ...

    @property
    def rows(self) -> int: ...
    @property
    def cols(self) -> int: ...
